In [1]:
import numpy as np

#Crear un arreglo
arr = np.arange(5)

#Guardar el arreglo en un archivo binario en el disco (extension .npy)
np.save('my_array',arr)

In [2]:
#Modificar el arreglo
arr = np.arange(10)
#Mostrar
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
#Observemos la copia original guardada
np.load('my_array.npy')

array([0, 1, 2, 3, 4])

In [4]:
#Guardar multiples arreglos en un archivo zip
np.savez('two_arrays.npz',x=arr,y=arr)

In [8]:
#Cargamos multiples arreglos
archive_array = np.load('two_arrays.npz')

#Mostrar
archive_array['x']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
import os

#Eliminemos los archivos de memoria
os.remove("my_array.npy")
os.remove("two_arrays.npz")

In [12]:
#Ahora guardamos y cargamos archivos de texto
arr = np.array([[1,2,3],[4,5,6]])
np.savetxt('my_test_text.txt',arr,delimiter=',')

In [13]:
arr = np.loadtxt('my_test_text.txt',delimiter = ',')
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])