In [1]:
import numpy as np

In [2]:
#Crear un arreglo
arr = np.arange(0,11)

#Mostrar
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
#Obtener el valor en un indice
arr[8]

8

In [4]:
#Obtener valores en un rango
arr[1:5]

array([1, 2, 3, 4])

In [5]:
#Asignar un valor en un rango (Broadcasting)
arr[0:5]=100

#Mostrar
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [6]:
#Reiniciar el arreglo
arr = np.arange(0,11)

#Mostrar
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
#Crear una particion del arreglo
slice_of_arr = arr[0:6]

#Mostrar la particion
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [8]:
#Cambiar particion
slice_of_arr[:]=99

#Mostrar
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [9]:
#Los cambios tambien ocurren en nuestro arreglo original!
arr

#Los datos no son copiados, es una vista del arreglo original! Esto evita problemas de memoria!

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [10]:
#Para obtener una copia, se tiene que hacer explicitamente
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [11]:
#Indexando un arreglo 2D

arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Mostrar
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [12]:
#Indexando una fila
arr_2d[1]

array([20, 25, 30])

In [13]:
#El formato es arr_2d[fila][columna]

#Obteniendo un elemento individual
arr_2d[1][0]

20

In [14]:
#Particionado de arreglo 2D

#Forma (2,2) de la esquina superior derecha
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [15]:
#Forma de la fila inferior
arr_2d[2]

array([35, 40, 45])

In [16]:
#Otra manera
arr_2d[2,:]

array([35, 40, 45])

In [18]:
#Indexado Lujoso

#Crear una matriz
arr2d = np.zeros((10,10))

#Longitud del arreglo
arr_length = arr2d.shape[1]

#Preparar arreglo
for i in range(arr_length):
    arr2d[i] = i

#Mostrar
arr2d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.]])

In [19]:
#Indexado lujoso permite lo siguiente
arr2d[[2,4,6,8]]

array([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.]])

In [20]:
#Lo permite en cualquier orden
arr2d[[6,4,2,7]]

array([[ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.]])