In [1]:
import numpy as np

#Las fucniones universales realizan operaciones sobre todos los elementos del arreglo

In [2]:
arr = np.arange(11)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
#Raiz cuadrada
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [4]:
#Exponencial (e^)
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [5]:
#Funciones binarias requieren 2 arreglos

#Arreglo aleatorio (distribucion normal)
A = np.random.randn(10)

A

array([ 0.48354044,  2.08392371,  0.58440885,  0.31774923,  0.07927299,
       -1.0233269 , -1.18936645,  2.06214995,  0.88156392, -2.22294596])

In [6]:
#Arreglo aleatorio (distribucion normal)
B = np.random.randn(10)
B

array([-0.17885705, -1.09550865,  0.35753464,  0.1332442 , -0.53717568,
       -1.85840067, -0.7510067 ,  0.3802929 ,  0.07707584, -0.878097  ])

In [7]:
#Adicion
np.add(A,B)

array([ 0.30468339,  0.98841506,  0.94194349,  0.45099343, -0.45790269,
       -2.88172758, -1.94037315,  2.44244285,  0.95863976, -3.10104297])

In [8]:
#Encontrar el maximo entre los dos arreglos
np.maximum(A,B)

array([ 0.48354044,  2.08392371,  0.58440885,  0.31774923,  0.07927299,
       -1.0233269 , -0.7510067 ,  2.06214995,  0.88156392, -0.878097  ])

In [9]:
#Lista extensiva de todas las funciones universales
website = "http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs"
import webbrowser
webbrowser.open(website)

True