In [1]:
import numpy as np

In [2]:
5/2

2.5

In [3]:
#Se hace cargo de los flotantes
from __future__ import division

In [4]:
#Crear arreglo
arr1 = np.array([[1,2,3],[8,9,10]])

#Mostrar
arr1

array([[ 1,  2,  3],
       [ 8,  9, 10]])

In [5]:
#Multiplicando arreglos
arr1 * arr1

array([[  1,   4,   9],
       [ 64,  81, 100]])

In [6]:
#Resta
arr1 - arr1

array([[0, 0, 0],
       [0, 0, 0]])

In [7]:
#Operaciones aritmeticas con escalares sobre arreglos
1 / arr1

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.125     ,  0.11111111,  0.1       ]])

In [8]:
#Operacion exponencial
arr1 ** 3

array([[   1,    8,   27],
       [ 512,  729, 1000]])